// LinqGen.Generator, Maxwell Keonwoo Kang <code.athei@gmail.com>, 2022

using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Cathei.LinqGen.Generator
{
    using static SyntaxFactory;
    using static CodeGenUtils;

    public static class GenerationTemplate
    {
        private static readonly SyntaxTree TemplateSyntaxTree = CSharpSyntaxTree.ParseText(@"// DO NOT EDIT
// Generated by LinqGen.Generator

using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Cathei.LinqGen;
using Cathei.LinqGen.Hidden;

namespace Cathei.LinqGen.Hidden
{
    // Enumerable is always readonly
    // Non-exported Enumerable should consider anonymous type, thus it will be internal
    internal readonly struct _Enumerable_ : _Interface_
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal _Enumerable_() : this()
        {

        }

        public int Count
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get
            {

            }
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Enumerator GetEnumerator()
        {
            return new Enumerator();
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Enumerator GetSliceEnumerator(int skip, int? take)
        {
            return new Enumerator();
        }

        public struct Enumerator : IEnumerator<_Element_>
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            internal Enumerator() : this()
            {

            }

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public bool MoveNext()
            {
            }

            public _Element_ Current
            {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get
                {

                }
            }

            object IEnumerator.Current => Current;

            void IEnumerator.Reset() => throw new NotSupportedException();

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void _Dispose_()
            {

            }
        }
    }
}

namespace Cathei.LinqGen
{
    // Extensions needs to be internal to prevent ambiguous resolution
    internal static partial class _Extensions_
    {
    }
}
");

        private class Rewriter : CSharpSyntaxRewriter
        {
            private readonly CompilingGeneration _instruction;

            public Rewriter(CompilingGeneration instruction)
            {
                _instruction = instruction;
            }

            public override SyntaxNode? VisitStructDeclaration(StructDeclarationSyntax node)
            {
                switch (node.Identifier.ValueText)
                {
                    case "_Enumerable_":
                        node = RewriteEnumerableStruct(node);
                        break;

                    case "Enumerator":
                        node = RewriteEnumeratorStruct(node);
                        break;
                }

                return base.VisitStructDeclaration(node);
            }

            public override SyntaxNode? VisitClassDeclaration(ClassDeclarationSyntax node)
            {
                switch (node.Identifier.ValueText)
                {
                    case "_Extensions_":
                        node = RewriteExtensionClass(node);
                        break;
                }

                return base.VisitClassDeclaration(node);
            }

            public override SyntaxNode? VisitConstructorDeclaration(ConstructorDeclarationSyntax node)
            {
                switch (node.Identifier.ValueText)
                {
                    case "_Enumerable_":
                        node = RewriteEnumerableConstructor(node);
                        break;

                    case "Enumerator":
                        node = RewriteEnumeratorConstructor(node);
                        break;
                }

                return base.VisitConstructorDeclaration(node);
            }

            public override SyntaxNode? VisitMethodDeclaration(MethodDeclarationSyntax node)
            {
                switch (node.Identifier.ValueText)
                {
                    case "GetEnumerator":
                        node = RenderGetEnumerator(node);
                        break;

                    case "GetSliceEnumerator":
                        if (!_instruction.IsPartition)
                            return null;

                        node = RenderGetSliceEnumerator(node);
                        break;

                    case "MoveNext":
                        node = RewriteEnumeratorMoveNext(node);
                        break;

                    // use _Dispose_ to prevent overwriting other Dispose in members
                    case "_Dispose_":
                        node = RewriteEnumeratorDispose(node);
                        break;
                }

                return base.VisitMethodDeclaration(node);
            }

            private MethodDeclarationSyntax RenderGetEnumerator(MethodDeclarationSyntax node)
            {
                return node.WithBody(_instruction.RenderGetEnumeratorBody());
            }

            private MethodDeclarationSyntax RenderGetSliceEnumerator(MethodDeclarationSyntax node)
            {
                return node.WithBody(_instruction.RenderGetSliceEnumeratorBody());
            }

            public override SyntaxNode? VisitPropertyDeclaration(PropertyDeclarationSyntax node)
            {
                switch (node.Identifier.ValueText)
                {
                    case "Current":
                        if (node.ExplicitInterfaceSpecifier == null)
                            node = RewriteEnumeratorCurrent(node);
                        break;

                    case "Count":
                        if (!_instruction.IsCountable)
                            return null;

                        node = RewriteEnumerableCount(node);
                        break;
                }

                return base.VisitPropertyDeclaration(node);
            }

            public override SyntaxNode? VisitIdentifierName(IdentifierNameSyntax node)
            {
                switch (node.Identifier.ValueText)
                {
                    case "_Enumerable_":
                        return _instruction.ResolvedClassName;

                    case "_Element_":
                        return _instruction.OutputElementType;

                    case "_Interface_":
                        return _instruction.InterfaceType;
                }

                return base.VisitIdentifierName(node);
            }

            private StructDeclarationSyntax RewriteEnumerableStruct(StructDeclarationSyntax node)
            {
                var additionalMembers = _instruction
                    .GetFieldDeclarations(MemberKind.Enumerable, true)
                    .Concat(GetAdditionalMembers());

                var baseListTypes = node.BaseList!.
                    Types.AddRange(_instruction.GetBaseInterfaces());

                return node.Update(node.AttributeLists, node.Modifiers, node.Keyword,
                    _instruction.IdentifierName.Identifier, _instruction.GetTypeParameters(),
                    node.BaseList.WithTypes(baseListTypes), _instruction.GetGenericConstraints(), node.OpenBraceToken,
                    node.Members.AddRange(additionalMembers), node.CloseBraceToken, node.SemicolonToken);
            }

            private StructDeclarationSyntax RewriteEnumeratorStruct(StructDeclarationSyntax node)
            {
                return node.AddMembers(_instruction.GetFieldDeclarations(MemberKind.Enumerator, false).ToArray());
            }

            private ClassDeclarationSyntax RewriteExtensionClass(ClassDeclarationSyntax node)
            {
                return node.WithIdentifier(
                        Identifier($"LinqGenExtensions_{_instruction.IdentifierName.Identifier.ValueText}"))
                    .AddMembers(GetExtensionMethods().ToArray());
            }

            private ConstructorDeclarationSyntax RewriteEnumerableConstructor(ConstructorDeclarationSyntax node)
            {
                return _instruction.RenderEnumerableConstructor();
            }

            private ConstructorDeclarationSyntax RewriteEnumeratorConstructor(ConstructorDeclarationSyntax node)
            {
                return _instruction.RenderEnumeratorConstructor();
            }

            private MethodDeclarationSyntax RewriteEnumeratorMoveNext(MethodDeclarationSyntax node)
            {
                return node.WithBody(_instruction.RenderMoveNextBody());
            }

            private MethodDeclarationSyntax RewriteEnumeratorDispose(MethodDeclarationSyntax node)
            {
                return node.WithIdentifier(DisposeMethod.Identifier)
                    .WithBody(_instruction.RenderDisposeBody());
            }

            private PropertyDeclarationSyntax RewriteEnumeratorCurrent(PropertyDeclarationSyntax node)
            {
                var getAccessor = node.AccessorList!.Accessors[0].WithBody(_instruction.RenderCurrentGetBody());
                return node.WithAccessorList(AccessorList(SingletonList(getAccessor)));
            }

            private PropertyDeclarationSyntax RewriteEnumerableCount(PropertyDeclarationSyntax node)
            {
                var getAccessor = node.AccessorList!.Accessors[0].WithBody(_instruction.RenderCountGetBody());
                return node.WithAccessorList(AccessorList(SingletonList(getAccessor)));
            }

            private IEnumerable<MemberDeclarationSyntax> GetAdditionalMembers()
            {
                foreach (var method in _instruction.RenderAdditionalMembers())
                    yield return method;
            }

            private IEnumerable<MemberDeclarationSyntax> GetExtensionMethods()
            {
                foreach (var method in _instruction.RenderExtensionMethods())
                    yield return method;

                if (_instruction.Evaluations != null)
                {
                    // evaluation can use specialization, so it should be extension method
                    foreach (var evaluation in _instruction.Evaluations)
                    {
                        yield return MethodDeclaration(new(AggressiveInliningAttributeList),
                            PublicStaticTokenList, evaluation.ReturnType, default,
                            evaluation.MethodName.Identifier, evaluation.GetTypeParameters(),
                            ParameterList(evaluation.GetParameters()), evaluation.GetGenericConstraints(),
                            evaluation.RenderMethodBody(), default, default);
                    }
                }
            }
        }

        public static SourceText Render(CompilingGeneration instruction)
        {
            var root = TemplateSyntaxTree.GetRoot();

            var rewriter = new Rewriter(instruction);
            root = rewriter.Visit(root);

            return root.NormalizeWhitespace().GetText(Encoding.UTF8);
        }
    }
}