using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace Cathei.LinqGen.Generator;

public static class FileRender
{
    private static readonly SyntaxTree Template = CSharpSyntaxTree.ParseText("""
// DO NOT EDIT
// Generated by LinqGen.Generator

#nullable disable

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using Cathei.LinqGen;
using Cathei.LinqGen.Hidden;

""");

    public static SourceText Render(CompilationUnitSyntax syntax)
    {
        var root = Template.GetCompilationUnitRoot();

        root = root.WithMembers(root.Members.AddRange(syntax.Members));

        return root.NormalizeWhitespace().GetText(Encoding.UTF8);
    }
}
