// LinqGen.Generator, Maxwell Keonwoo Kang <code.athei@gmail.com>, 2022

using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Cathei.LinqGen.Generator
{
    using static SyntaxFactory;
    using static CodeGenUtils;

    public static class AsEnumerableTemplate
    {
        private static readonly SyntaxTree TemplateSyntaxTree = CSharpSyntaxTree.ParseText(@"// DO NOT EDIT
// Generated by LinqGen.Generator

using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Cathei.LinqGen;
using Cathei.LinqGen.Hidden;
using Cathei.LinqGen.Hidden._Assembly_;

namespace Cathei.LinqGen.Hidden._Assembly_
{
    // result of AsEnumerable, don't need to be public
    internal class _Enumerable_ : IEnumerable<_Element_>
    {
        private readonly _Upstream_ source;

        internal _Enumerable_(in _Upstream_ source)
        {
            this.source = source;
        }

        public IEnumerator<_Element_> GetEnumerator() => source.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
    }
}

namespace Cathei.LinqGen
{
    // Extensions needs to be internal to prevent ambiguous resolution
    internal static partial class _Extensions_
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static IEnumerable<_Element_> AsEnumerable(this _Upstream_ source)
        {
            return new _Enumerable_(source);
        }
    }
}
");

        private class Rewriter : CSharpSyntaxRewriter
        {
            private readonly IdentifierNameSyntax _assemblyName;
            private readonly AsEnumerableOperation _instruction;

            public Rewriter(IdentifierNameSyntax assemblyName, AsEnumerableOperation instruction)
            {
                _assemblyName = assemblyName;
                _instruction = instruction;
            }

            public override SyntaxNode? VisitClassDeclaration(ClassDeclarationSyntax node)
            {
                switch (node.Identifier.ValueText)
                {
                    case "_Enumerable_":
                        node = RewriteEnumerableClass(node);
                        break;

                    case "_Extensions_":
                        node = RewriteExtensionClass(node);
                        break;
                }

                return base.VisitClassDeclaration(node);
            }

            public override SyntaxNode? VisitConstructorDeclaration(ConstructorDeclarationSyntax node)
            {
                switch (node.Identifier.ValueText)
                {
                    case "_Enumerable_":
                        node = RewriteEnumerableConstructor(node);
                        break;
                }

                return base.VisitConstructorDeclaration(node);
            }

            public override SyntaxNode? VisitMethodDeclaration(MethodDeclarationSyntax node)
            {
                switch (node.Identifier.ValueText)
                {
                    case "AsEnumerable":
                        node = RewriteExtensionMethod(node);
                        break;
                }

                return base.VisitMethodDeclaration(node);
            }

            public override SyntaxNode? VisitIdentifierName(IdentifierNameSyntax node)
            {
                switch (node.Identifier.ValueText)
                {
                    case "_Enumerable_":
                        if (_instruction.Arity == 0)
                            return _instruction.IdentifierName;
                        return GenericName(_instruction.IdentifierName!.Identifier, _instruction.GetTypeArguments()!);

                    case "_Element_":
                        return _instruction.ElementName;

                    case "_Upstream_":
                        return _instruction.UpstreamResolvedClassName;

                    case "_Assembly_":
                        return _assemblyName;
                }

                return base.VisitIdentifierName(node);
            }

            private ClassDeclarationSyntax RewriteEnumerableClass(ClassDeclarationSyntax node)
            {
                return node.WithIdentifier(_instruction.IdentifierName!.Identifier)
                    .WithTypeParameterList(_instruction.GetTypeParameters())
                    .WithConstraintClauses(_instruction.GetGenericConstraints());
            }

            private ClassDeclarationSyntax RewriteExtensionClass(ClassDeclarationSyntax node)
            {
                return node.WithIdentifier(
                    Identifier($"LinqGenExtensions_{_instruction.IdentifierName!.Identifier.ValueText}"));
            }

            private ConstructorDeclarationSyntax RewriteEnumerableConstructor(ConstructorDeclarationSyntax node)
            {
                return node.WithIdentifier(_instruction.IdentifierName!.Identifier);
            }

            private MethodDeclarationSyntax RewriteExtensionMethod(MethodDeclarationSyntax node)
            {
                return node.WithTypeParameterList(_instruction.GetTypeParameters())
                    .WithConstraintClauses(_instruction.GetGenericConstraints());
            }
        }

        public static SourceText Render(IdentifierNameSyntax assemblyName, AsEnumerableOperation instruction)
        {
            var root = TemplateSyntaxTree.GetRoot();

            var rewriter = new Rewriter(assemblyName, instruction);
            root = rewriter.Visit(root);

            return root.NormalizeWhitespace().GetText(Encoding.UTF8);
        }
    }
}