// LinqGen.Generator, Maxwell Keonwoo Kang <code.athei@gmail.com>, 2022

using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace Cathei.LinqGen.Generator;

public static class FileTemplate
{
    private static readonly SyntaxTree TemplateSyntaxTree = CSharpSyntaxTree.ParseText(@"// DO NOT EDIT
// Generated by LinqGen.Generator

#nullable disable

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using Cathei.LinqGen;
using Cathei.LinqGen.Hidden;

");

    public static SourceText Render(IEnumerable<MemberDeclarationSyntax> members)
    {
        var root = TemplateSyntaxTree.GetCompilationUnitRoot();

        root = root.AddMembers(members.ToArray());

        return root.NormalizeWhitespace().GetText(Encoding.UTF8);
    }
}