// LinqGen.Generator, Maxwell Keonwoo Kang <code.athei@gmail.com>, 2022

using System.Linq;
using System.Reflection;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Cathei.LinqGen.Generator
{
    using static SyntaxFactory;
    using static CodeGenUtils;

    public static class GenerationTemplate
    {
        private static readonly SyntaxTree TemplateSyntaxTree = CSharpSyntaxTree.ParseText(@"// DO NOT EDIT
// Generated by LinqGen.Generator

using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Cathei.LinqGen;
using Cathei.LinqGen.Hidden;

namespace Cathei.LinqGen.Hidden
{
    // Non-exported Enumerable should consider anonymous type, thus it will be internal
    internal struct _Enumerable_ : IInternalStub<_Element_>
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal _Enumerable_() : this()
        {

        }
    }
}

// static classes needs to be internal to prevent ambiguous resolution
namespace Cathei.LinqGen
{
    internal static partial class GenEnumerable
    {
    }

    internal static partial class _Extensions_
    {
    }
}
");

        private class Rewriter : CSharpSyntaxRewriter
        {
            private readonly Generation _instruction;

            public Rewriter(Generation instruction)
            {
                _instruction = instruction;
            }

            public override SyntaxNode? VisitClassDeclaration(ClassDeclarationSyntax? node)
            {
                switch (node!.Identifier.ValueText)
                {
                    case "GenEnumerable":
                        node = RewriteGenEnumerableClass(node);
                        break;

                    case "_Extensions_":
                        node = RewriteExtensionClass(node);
                        break;
                }

                return node == null ? null : base.VisitClassDeclaration(node);
            }

            public override SyntaxNode? VisitStructDeclaration(StructDeclarationSyntax node)
            {
                switch (node.Identifier.ValueText)
                {
                    case "_Enumerable_":
                        node = RewriteEnumerableStruct(node);
                        break;
                }

                return base.VisitStructDeclaration(node);
            }

            public override SyntaxNode? VisitConstructorDeclaration(ConstructorDeclarationSyntax node)
            {
                switch (node.Identifier.ValueText)
                {
                    case "_Enumerable_":
                        node = RewriteEnumerableConstructor(node);
                        break;
                }

                return base.VisitConstructorDeclaration(node);
            }

            public override SyntaxNode? VisitIdentifierName(IdentifierNameSyntax node)
            {
                switch (node.Identifier.ValueText)
                {
                    case "_Element_":
                        return _instruction.OutputElementType;

                    case "_Enumerable_":
                        return _instruction.ResolvedClassName;

                    // case "_Interface_":
                    //     return _instruction.InterfaceType;
                }

                return base.VisitIdentifierName(node);
            }

            private ClassDeclarationSyntax? RewriteGenEnumerableClass(ClassDeclarationSyntax node)
            {
                var staticMethods = _instruction.RenderPredefinedClassMembers().ToArray();

                if (staticMethods.Length == 0)
                    return null;

                return node.AddMembers(staticMethods);
            }

            private ClassDeclarationSyntax? RewriteExtensionClass(ClassDeclarationSyntax node)
            {
                var extensionMethods = _instruction.RenderExtensionClassMembers().ToArray();

                if (extensionMethods.Length == 0)
                    return null;

                return node
                    .WithIdentifier(Identifier($"LinqGenExtensions_{_instruction.ClassName.Identifier.ValueText}"))
                    .AddMembers(extensionMethods);
            }

            private StructDeclarationSyntax RewriteEnumerableStruct(StructDeclarationSyntax node)
            {
                return node.WithIdentifier(_instruction.ClassName.Identifier)
                    .WithTypeParameterList(_instruction.GetTypeParameters())
                    .WithConstraintClauses(_instruction.GetGenericConstraints())
                    .AddMembers(_instruction.RenderEnumerableMembers().ToArray())
                    .AddMembers(_instruction.GetFieldDeclarations(MemberKind.Enumerable).ToArray());
            }

            private ConstructorDeclarationSyntax RewriteEnumerableConstructor(ConstructorDeclarationSyntax node)
            {
                return node.WithIdentifier(_instruction.ClassName.Identifier)
                    .WithParameterList(ParameterList(_instruction.GetParameters(MemberKind.Enumerable, true)))
                    .WithBody(Block(_instruction.GetFieldAssignments(MemberKind.Enumerable)));
            }
        }

        public static SourceText Render(Generation instruction)
        {
            var root = TemplateSyntaxTree.GetRoot();

            var rewriter = new Rewriter(instruction);
            root = rewriter.Visit(root);

            return root.NormalizeWhitespace().GetText(Encoding.UTF8);
        }
    }
}