// LinqGen.Generator, Maxwell Keonwoo Kang <code.athei@gmail.com>, 2022

using System;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Cathei.LinqGen.Generator
{
    public static class GenerationFormatter
    {
        private const string SourceTemplate = @"// DO NOT EDIT
// Generated by LinqGen.Generator

using System.Collections.Generic;

namespace Cathei.LinqGen.Hidden
{{
    using Operations;

    public readonly struct {0}_{1} : ILinqGenEnumerable<{2}, NoOp>
    {{
        private readonly IEnumerable<{2}> source;

        internal {0}_{1}(IEnumerable<{2}> source)
        {{
            this.source = source;
        }}

        public IEnumerator<{2}> GetEnumerator() => source.GetEnumerator();
    }}
}}

namespace Cathei.LinqGen
{{
    using Hidden;

    public static partial class LinqGenExtensions
    {{
        public static {0}_{1} Generate(this IEnumerable<{2}> source)
            => new {0}_{1}(source);
    }}
}}
";

        public static void Format(StringBuilder builder, GenerationItem item, int id)
        {
            string shortName = Constants.Op.ShortName[Constants.Op.Gen];
            string elementFullName = item.ElementTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            builder.AppendFormat(SourceTemplate, shortName, id, elementFullName);
        }
    }
}